(ns skip.dmtools.npc.resources
    (:require [clojure.spec.alpha :as s]))

(def tiefling-lname [
"Ambition"
"Art"
"Carrion"
"Chant"
"Creed"
"Death"
"Debauchery"
"Despair"
"Doom"
"Doubt"
"Dread"
"Ecstasy"
"Ennui"
"Entropy"
"Excellence"
"Fear"
"Glory"
"Gluttony"
"Grief"
"Hate"
"Hope"
"Horror"
"Ideal"
"Ignominy"
"Laughter"
"Love"
"Lust"
"Mayhem"
"Mockery"
"Murder"
"Muse"
"Music"
"Mystery"
"Nowhere"
"Open"
"Pain"
"Passion"
"Poetry"
"Quest"
"Random"
"Reverence"
"Revulsion"
"Sorrow"
"Temerity"
"Torment"
"Tragedy"
"Vice"
"Virtue"
"Weary"
"Wit"
])

(def halfling-lname [
"Appleblossom"
"Bigheart"
"Brightmoon"
"Brushgather"
"Cherrycheeks"
"Copperkettle"
"Deephollow"
"Elderberry"
"Fastfoot"
"Fatrabbit"
"Glenfellow"
"Goldfound"
"Goodbarrel"
"Goodearth"
"Greenbottle"
"Greenleaf"
"High-hill"
"Hilltopple"
"Hogcollar"
"Honeypot"
"Jamjar"
"Kettlewhistle"
"Leagallow"
"Littlefoot"
"Nimblefingers"
"Porridgepot"
"Quickstep"
"Reedfellow"
"Shadowquick"
"Silvereyes"
"Smoothhands"
"Stonebridge"
"Stoutbridge"
"Stoutman"
"Strongbones"
"Sunmeadow"
"Swiftwhistle"
"Tallfellow"
"Tealeaf"
"Te11Penny"
"Thistletop"
"Thorngage"
"Tosscobble"
"Underbough"
"Underfoot"
"Warmwater"
"Whispermouse"
"Wildcloak"
"Wildheart"
"Wiseacre"
])

(def gnome-lname [
"Albaratie"
"Bafflestone"
"Beren"
"Boondiggles"
"Cobblelob"
"Daergel"
"Dunben"
"Fabblestabble"
"Fapplestamp"
"Fiddlefen"
"Folkor"
"Garrick"
"Gimlen"
"Glittergem"
"Gobblefirn"
"Gummen"
"Horcusporcus"
"Humplebumple"
"lronhide"
"Leffery"
"Lingenhall"
"Loofollue"
"Maekkelferce"
"Miggledy"
"Munggen"
"Murnig"
"Musgraben"
"Nackle"
"Ningel"
"Nopenstallen"
"Nucklestamp"
"Offund"
"Oomtrowl"
"Pilwicken"
"Pingun"
"Quillsharpener"
"Raulnor"
"Reese"
"Rofferton"
"Scheppen"
"Shadowcloak"
"Silverthread"
"Sympony"
"Tarkelby"
"Timbers"
"Turen"
"Umbodoben"
"Waggletop"
"Welber"
"Wildwander"
])
(def elf-lname [
"Dalanthan"
"Eathalena"
"Erenaeth"
"Ethanasath"
"Fasharash"
"Firahel"
"Floshem"
"Galanodel"
"Goltorah"
"Hanali"
"Holimion"
"Horineth"
"lathrana"
"llphelkiir"
"lranapha"
"Koehlanna"
"Lathalas"
"Liadon"
"Meliamne"
"Mellerelel"
"Mystralath"
"Nailo"
"Netyoive"
"Ofandrus"
"Ostoroth"
"Othronus"
"Qualanthri"
"Raethran"
"Rothenel"
"Selevarun"
"Siannodel"
"Suithrasas"
"Sylvaranth"
"Teinithra"
"Tiltathana"
"Wasanthi"
"Withrethin"
"Xiloscient"
"Xistsrith"
"Yaeldrin"
])

(def dwarf-lname [
"Aranore"
"Balderk"
"Battlehammer"
"Bigtoe"
"Bloodkith"
"Bofdann"
"Brawnanvil"
"Brazzik"
"Broodfist"
"Burrowfound"
"Caebrek"
"Daerdahk"
"Dankil"
"Daraln"
"Deepdelver"
"Durthane"
"Eversharp"
"Fallack"
"Fireforge"
"Foamtankard"
"Frostbeard"
"Glanhig"
"Goblinbane"
"Goldfinder"
"Gorunn"
"Graybeard"
"Hammerstone"
"Helcral"
"Holderhek"
"lronfist"
"Loderr"
"Lutgehr"
"Morigak"
"Orcfoe"
"Rakankrak"
"Ruby-Eye"
"Rumnaheim"
"Silveraxe"
"Silverstone"
"Steelfist"
"Stoutale"
"Strakeln"
"Strongheart"
"Thrahak"
"Torevir"
"Torunn"
"Trollbleeder"
"Trueanvil"
"Trueblood"
"Ungart "
])
(def dragonborn-lname [
    "Akambherylliax"
    "Argenthrixus"    
    "Baharoosh"       
    "Beryntolthropal" 
    "Bhenkumbyrznaax "
    "Caavylteradyn   "
    "Chumbyxirinnish "
    "Clethtinthiallor"
    "Daardendrian    "
    "Delmirev        "
    "Dhyrktelonis    "
    "Ebynichtomonis  "
    "Esstyrlynn      "
    "Fharngnarthnost "
    "Ghaallixirn     "
    "Grrrmmballhyst  "
    "Gygazzylyshrift "
    "Hashphronyxadyn "
    "Hshhsstoroth    "
    "lmbixtellrhyst  "
    "Jerynomonis     "
    "Jharthraxyn     "
    "Kerrhylon      "
    "Kimbatuul      "
    "Lhamboldennish  "
    "Linxakasendalor "
    "Mohradyllion    "
    "Mystan          "
    "Nemmonis        "
    "Norixius        "
    "Ophinshtalajiir "
    "Orexijandilin"
    "Pfaphnyrennish"
    "Phrahdrandon"
    "Pyraxtallinost"
    "Qyxpahrgh "
    "Raghthroknaar"
    "Shestendeliath"
    "Skaarzborroosh"
    "Sumnarghthrysh"
    "Tiammanthyllish"
    "Turnuroth"
    "Umbyrphrael"
    "Vangdondalor"
    "Verthisathurgiesh"
    "Wivvyrholdalphiax"
    "Wystongjiir"
    "Xephyrbahnor"
    "Yarjerit"
    "Zzzxaaxthroth"
    ])


        
;;NPC MANNERISMS
(def mannerisms [
    "Prone to singing, whistling, or humming quietly"
    "Speaks in rhyme or some other peculiar way"
    "Particularly low or high voice"
    "Slurs words, lisps, or stutters"
    "Enunciates overly clearly"
    "Speaks loudly"
    "Whispers"
    "Uses flowery speech or long words"
    "Frequently uses the wrong word"
    "Uses colorful oaths and exclamations"
    "Makes constant jokes or puns"
    "Prone to predictions of doom"
    "Fidgets"
    "Squints"
    "Stares into the distance"
    "Chews something"
    "Paces"
    "Taps fingers"
    "Bites fingernails"
    "Twirls hair or tugs beard "
    ])
    
    (def quirks [
    "Always bored"
    "Angry drunk"
    "Annoyingly Cryptic"
    "Avant-garde"
    "Bigoted"
    "Bloody-Minded"
    "Boastful"
    "Bookworm"
    "Bossy"
    "Bully"
    "Calculating"
    "Can-do attitude"
    "Chatterbox"
    "Chirpy"
    "Collects small animals"
    "Compulsive Liar"
    "Condescending"
    "Conniving"
    "Conspiracy theorist"
    "Creep"
    "Decadent"
    "Ditz"
    "Egomaniac"
    "Exquisite dresser"
    "Extravagant"
    "Fanatically loyal"
    "Fast-talker"
    "Femme Fatale"
    "Fiercely ambitious"
    "Fits of melancholy"
    "Flamboyant"
    "Folksy Wisdom"
    "Gossip"
    "Hard-boiled"
    "Hears voices"
    "Hillbilly"
    "Hothead"
    "Hypochondriac"
    "Iconoclast"
    "Idealistic"
    "Illiterate"
    "Incredibly persistent"
    "Insightful observer"
    "Into crystals"
    "Jack of all Trades"
    "Jerk"
    "Klutz"
    "Knows everybody"
    "Life of the party"
    "Love-struck"
    "Mad genius"
    "Magnetic Personality"
    "Manic"
    "Master Orator"
    "Militantly Vegan"
    "Misanthrope"
    "Miser"
    "Mopey"
    "Naïve"
    "Nerd"
    "No-nonsense"
    "Obsessive"
    "Old Fart"
    "Overeducated"
    "Paranoid"
    "Perfect Manners"
    "Pouty"
    "Power-hungry"
    "Prickly"
    "Proselytizer"
    "Ruthless"
    "Sadist"
    "Self-destructive"
    "Self-important"
    "Self-pitying"
    "Senile"
    "Serene"
    "Shameless Flirt"
    "Slacker"
    "Slimy"
    "Slovenly"
    "Snarky"
    "Snitch"
    "Snob"
    "Social butterfly"
    "Sophist"
    "Spacey"
    "Terrible memory"
    "Thick"
    "Toady"
    "Totally unreliable"
    "Twitchy"
    "Vain"
    "Vengeful"
    "Village idiot"
    "Well-Travelled"
    "Whiner"
    "Wild Child"
    "Wisecracking"
    "World-weary"
    "NPC rubs the back of his neck as he speaks. (Is he nervous? Was he hit?)"
    "Conceited, obnoxiously so."
    "NPC has no fingernails (You learn he survived torture.)"
    "Jingles gold pieces in pocket."
    "Says 'hmmm hmmm' often. (Habit or is he that agreeable?)"
    "Asks rhetorical questions."
    "Falsely claims he was an adventurer too."
    "She nods often."
    "She carries satchel filed with junk."
    "Sweats."
    "Shaving cuts on face (Interesting if this was a Dwarf who had shaved.)"
    "Military mannerisms, clear in how he carries himself."
    "She has an animal claw scar that is highly visible."
    "Always out of breath."
    "Rolls 'Rs' (Good luck to the DM roleplaying this!)"
    "She snorts when laughing (It’s endearing.)"
    "Complains of heartburn."
    "Rings sewn all over his/her clothes."
    "Clothes made of woven leaves, yet lives in town."
    "Carries cloth covered basket (What is in there?)"
    "Spit polished bracelet that clearly holds personal meaning."
    "Hard of hearing to hilarious results."
    "NPC gives himself a different name every meeting."
    "She blows stray hair out of eyes."
    "Dude hooks thumbs in his belt when he stands."
    "Sways nervously."
    "Carries small lizard."
    "Long manicured nails."
    "Blind, but looks through familiar’s eyes."
    "Instructs PCs in latest fashion, yet looks a little silly."
    "Rubs large belly as he (she?) talks."
    "Pouts."
    "Calls PCs by wrong names consistently."
    "Giggles endearingly."
    "Wine colored birthmark highly visible on body."
    "Polishes odd eyepieces, but never puts them on."
    "Sunburned."
    "Picks lint off PCs clothes."
    "Always asks for a bite of whatever someone is eating."
    "Has black eye."
    "Mixes languages during every conversation."
    "Keeps hand on PCs shoulder when speaking to them."
    "Feeds crumbs to birds."
    "Hands coppers to beggar kids."
    "Has immaculately spotless boots."
    "Rope burns around wrists."
    "Hair dye on collar"
    "Armor is covered in strange runes."
    "Nose bleeds."
    "Refers to good ‘ole days in every conversation."
    "Hopelessly optimistic."
    "Has a heart shape cut into skin."
    "Ogles opposite sex openly."
    "Ink stained fingers."
    "Gap between teeth."
    "Always scratching a rash."
    "Missing 7th finger."
    "Rubs hands together when he speaks."
    "She stares off when speaking."
    "He has long pauses when speaking."
    "Facial piercings."
    "Tugs on ear."
    "Rubs chin as in deep thought."
    "Cleans nails with knife as he speaks."
    "Single beard braid."
    "Out of touch clothing (Perhaps even unusual for the environment.)"
    "Smells like horses."
    "Smells like alcohol."
    "Leaves in hair always."
    "Sniffs the air."
    "Unusual jewelry."
    "Freckled."
    "Highly superstitious."
    "Loud talker (Or maybe close talker.)"
    "Makes puns."
    "Makes plans."
    "Is always chewing on a stick."
    "Smacks palm with fist."
    "Asks often about own appearance."
    "Rubs palms on thighs."
    "Invades personal space on every meeting."
    "Repeats things back to you."
    "Oily skin."
    "Doesn’t let things go."
    "Has long pauses before talking."
    "Obvious cosmetics."
    "Obvious wig."
    "Belches often."
    "Openly racist."
    "Complements sincerely."
    "Talks often about seeing the world some day."
    "Always carries fresh cut flowers"
    "Has an engorged leech on hand."
    "Keeps a goat on a leash."
    "Sharpens knife incessantly."
    "Always practicing a fire starting cantrip."
    "Mutters to himself and twitches."
    "Carves simple animal figurines for children."
    "Has name monogrammed on the back of his tunic."
    "Has a wizard hat covered in fish hooks."
    ])
    
    ;;NPC BONDS
    (def bonds [
    "Dedicated to fulfilling a personal life goal"
    "Protective of close family members"
    "Protective of colleagues or compatriots"
    "Loyal to a benefactor, patron, or employer"
    "Captivated by a romantic interest"
    "Drawn to a special place"
    "Protective of a sentimental keepsake"
    "Protective of a valuable possession"
    "Out for revenge"
    ])
    
    (def flaws [
    "Forbidden love or susceptibility to romance"
    "Enjoys decadent pleasures"
    "Arrogance"
    "Envies another creature's possessions or station"
    "Overpowering greed"
    "Prone to rage"
    "Has a powerful enemy"
    "Specific phobia"
    "Shameful or scandalous history"
    "Secret crime or misdeed"
    "Possession of forbidden lore"
    "Foolhardy bravery "
    ])
    
    (def calm [
    "Compassionate"
    "Cheerful"
    "Reserved"
    "Outspoken"
    "Uninterested"
    "Gruff"
    "Eager"
    "Deceitful"
    "Foolish"
    "Strict"
    "Agreeable"
    "Mischeivious"
    "Angry"
    "Fearful"
    "Manipulative"
    "Devout"
    "Greedy"
    "Funny"
    "Dour"
    "Fun-Loving"
    "Lazy"
    "Driven"
    "Boastful"
    "Artistic"
    "Assertive"
    "Carefree"
    "Cautious"
    "Confident"
    "Thoughtful"
    "Loyal"
    "Sophisticated"
    "Weak-Willed"])
    
    (def stress [
    "Withdrawn"
    "Murderous"
    "Obsessive"
    "Authoritarian"
    "Determined"
    "Brave"
    "Spiteful"
    "Belligerent"
    "Caustic"
    "Reckless"
    "Argumentative"
    "Gluttonous"
    "Overly Protective"
    "Angry"
    "Cowardly"
    "Meticulous"
    "Sarcastic"
    "Stubborn"
    "Destructive"
    "Practical"
    "Pushy"
    "Fanatical"
    "Secretive"
    "Scornful"
    "Courageous"
    "Impractical"
    "Calculating"
    "Industrious"
    "Manipulative"
    "Destructive"
    "Compulsive"
    "Intolerant"
    ])
    
    (def demeanor [
    "Agreeable"
    "Disagreeable"
    "Indifferent"
    ])
        
    (def prejudice [
    "Elves"
    "Dwarves"
    "Gnomes"
    "Halflings"
    "Humans"
    "Tieflings"
    "Dragonborn"
    "Drow"
    "Genasi"
    "Females"
    "Males"
    "Children"
    "Elderly"
    "The powerful rich"
    "The destitute poor"
    "Authority"
    "Performers/Music"
    "Laborers/Farmers"
    "Magic-users"
    "Clergy/Religion"
    "Merchants"
    "Humans"
    "Sailors/Soldiers"
    "Students/Scholars"
    "Drug users/Drinkers"
    ])
    (def faith [
        "Quiet true believer"
        "Casual observer"
        "Critical student"
        "Outspoken cynic"
        "Open-minded seeker"
        "Broken heretic"
        "Cautious listener"
        "Fanatical true believer"
    ])
        
    (s/conform ::appearance (zipmap keys values))
    ))

(def appearance ["Distinctive jewelry: earrings, necklace, circlet, bracelets"
"Piercings"
"Flamboyant or outlandish clothes"
"Formal, clean clothes"
"Ragged, dirty clothes"
"Pronounced scar"
"Missing teeth"
"Missing fingers"
"Unusual eye color (or two different colors)"
"Tattoos"
"Birthmark"
"Unusual skin color"
"Bald"
"Braided beard or hair"
"Unusual hair color"
"Nervous eye twitch"
"Distinctive nose"
"Distinctive posture (crooked or rigid)"
"Exceptionally beautiful"
"Exceptionally ugly "
"A long, glorious beard. Each braid represents another person that has asked him what the braids mean. "
"has a cleft cut into their nose. "
"has many tiny tattoos across their face starting from the corner of their mouth to the edge of their eye. "
"has an extra hand coming out of their right arm the hand is as small as a child’s and is blackened and seems to be of no use. "
"is missing a tooth. "
"One of the NPC’s arms is a different tone, length, and has a different shape of hand than the other. "
"has been cursed to have a part of their body, (arm, leg, hand, maybe even a tail...) that is of a different race. (ex. A human with the hand of a tabaxi...) "
"has many scars and callouses along their forearms, perhaps being formed over many brutal sparring sessions. "
"has long, slender fingers, perhaps from living an easy life in the high class or perhaps from living a life scrounging in the streets. "
"has well-toned leg muscles. Clearly, they are used to running. "
"has bags under their eyes, perpetually unable to sleep a full night. "
"has meticulously groomed hair (beard and mustache as well, if applicable) and is almost never seen with an out-of-place hair. "
"wears an array of gaudy and flamboyant jewellery, supporting itself on a cane embedded with a poorly cut ruby too big to be real. It's ears sport a multitude of filigree ear rings, as if to distract from it crooked and yellow teeth. "
"The npc's eyes change color with their mood. "
"is abnormally tall/short for their race. "
"The NPC's left hand has steel claws that appear to be artificially attached. "
"has a very faint tattoo on their forehead that requires a DC 15 Investigation check to make out clearly. The tattoo is enchanted to cast suggestion on someone who successfully investigates the tattoo. The suggestion is 'Stop looking at my forehead.' "
"If a man, has a surprisingly large butt/hips. "
"has no hair. "
"has a mohawk. "
"has a beard with beads in it. "
"has half of their hair blonde, and has one blonde eye on the same side. "
"is carrying a large sack. On the sack are the letters TBD. "
"doesn't have eyebrows, but instead has tattooed eyebrows slightly too high, which gives a look of permanent surprise. "
"is covered in tattoos of the cities they have been to. Each one best representing that city. "
"has a mouth on their back that says mean stuff about them. This would usually sadden people but this just pushes them to complete their goals more. "
"has a horn coming out of their forehead that they are very self conscious about. They constantly shave it off if they have time. "
"has scales on his legs. (If they are a species that usually has scales then their legs are human.) "
"has no natural teeth left. Luckily for him his enemies had some of theres. His jaw is full of random teeth that are surgically placed in. They may not be fabulous but they sure is scary! "
"has a magical tattoo that can answer riddles. "
"is missing his left eye. He constantly forgets which eye is actually gone. "
"has acid burn scars on both of his hands. "
"is fascinated by jewelry so much so that they are wearing so much jewelry that it weighs them down. "
"has a scar around their neck. "
"has orange eyes that glow when near heroic people. "
"has white eyes that glow when near neutral good to lawful good holy symbols. "
"has red eyes that glow when near blood. "
"has green eyes that glow when near poison. "
"NPC is extremely muscular but lazy in actions. "
"has bright yellow hair that glows in the dark. "
"has the tail of a rat. "
"NPC is blinded in daylight but can see perfectly in the dark. "
"NPC was given a curse by a witch when he was a child and now has a finger on his right arm that points in the direction of the closest person that wants to kill him. "
"has a extremely chapped lips. "
"has a tattoo of a map leading to an X. Doesn't remember when it got there or why it's there. "
"has a mechanical limb that they cannot fully control. It does the motion for whatever he is thinking even if it's socially wrong. "
"has a horrid burn mark running down from their left elbow to their hand. "
"is missing his/her left arm, and doesn't seem quite used to functioning without it. "
"has a jewel implanted in the place of a lost eye. "
"has a distracting mole. "
"has one long fingernail, presumably left unfiled for strumming an instrument. "
"has a violet bruise on the bone of their cheek. "
"has acne scars pockmarked across their face. "
"has a snaggletooth long enough to be a fang. "
"has one leg severely deformed they carry themselves around on double crutches. "
"has a pair of thick spectacles that don't fit. "
"has thick, greasy dreadlocks from years of improper washing. "
"has one eye swollen over from a recent fight. "
"The NPC's mouth is permanently crooked, giving them a cocky smirk even in serious moments. "
"has not cut or groomed his/her hair since he/she was defeated by his/her rival 8 years ago. "
"Scars... Everywhere. "
"has a beard that is visibly fake. "
"has an eye on the palm of his/her right hand that he/she tries to hide with a fingerless glove. "
"has one blue eye and one brown. "
"NPC's face has splotches the color of red wine. "
"has a sparse beard, like underarm hair. "
"has bushy eyebrows that waggle when they talk. "
"has no nose. He has one big hole where the nose was supposed to be. "
"NPC walks with a significant limp requiring a cane to help them walk. "
"has a very muscular upper body, but their legs look very underdeveloped. "
"Male NPC talks with a define lisp and tends be be flamboyant with arm gestures. "
"has 6 fingers. "
"NPC is androgynous. Very difficult to glean gender. "
"has a Hunchback and disfigured face with extra growths. "
"has whats left of a hand still attached. It looks like it was crushed and was never amputated. "
"has abnormally large forearms and/or calves. "
"is wearing an obvious wig. "
"The NPCs left eye has three pupils. "
"constantly smells of rosemary and brimstone. "
"has a long pointy nose that curls and wiggles according the NPCs emotions. "
"A holy symbol is branded onto the NPCs right hand. "
"The NPCs teeth are made out of various rare metals. "
"Exotic runes are carved on the NPCs forearm. "
"NPCs hands are stained multiple colors. "
"has a forked tongue "
"has piercings all over their body. Bars and rings cover them. "
"NPC is blind/deaf. "
"has ashen skin and no hair. "
"has sharpened teeth and loves to smile. "
"NPC is unusually hairy, having thick hair on almost all visible skin apart from around eyes and palms. "
"NPC always wears bright, vibrant clothing. "
"NPC constantly twitches. They can not stay still. "
"The skin on the NPCs left forearm is transparent. "
"There are small mushrooms on the back of the NPCs neck. "
"has small woodland critters in their hair. "
"uses overly-exagerated movements for everything. "
"is slowly rotting away. "
"has incredibly beautiful features. One of the most beautiful people you have ever seen! "
])

(def modifier [
"fine " "tattered " ""     
])

(def clothing [
    "leather armor" "steel breastplate" "linen gambeson"
    "clothing" "silk robes" "velvet cape" "heavy cloak" "frock"    
])
    